### PR TITLE
Initiate CLA - Dirk Brinkmann

### PR DESCRIPTION
**Pull request by DirkBrinkmann**

### CODE REVIEW

**Comment by jpradocueva** [comment]
@DirkBrinkmann, please get in contact via focus@finops.org if your company is having problems signing the Contributor License Agreement, (CLA).

**Comment by flanakin** [comment]
@jpradocueva, Dirk is at Microsoft. I had him link his @microsoft.com email address to his LF account and make it primary, but it's still not going green. Not sure if we missed anything.

**Comment by DirkBrinkmann** [comment]
@jpradocueva @flanakin I have also linked my LF Profile with my GitHub Account. Still no success :)

**Comment by jpradocueva** [comment]
@DirkBrinkmann, please make sure your company email is listed in your GitHub profile. If you updated your email after submitting the PR and it's still not working, consider creating a new PR. If the issue persists, please contact our helpline for assistance at [Get Help with LFX EasyCLA](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/create/143)”.

**Pull request closed without merging**
